<template>
  <div id="" class="px-0 container-fluid">
    <div id="row" class="grid grid-rows-1">
      <div id="content" class="bg-slate-950">
        <div
          id=""
          class="grid grid-cols-1 2xl:columns-1 xl:columns-1 lg:columns-1 md:columns-1 sm:columns-1 xs:columns-1"
        >
          <span id="sectionHeading" class="">
            <h1>Certifications And Achievements</h1>
          </span>
        </div>
        <div
          id=""
          class="grid grid-cols-1 2xl:columns-1 xl:columns-1 lg:columns-1 md:columns-1 sm:columns-1 xs:columns-1"
        >
          <div id="" class="align-middle text-center">
            <span id="" class="">
              <p id="" class="certificationTitle">Introduction to Data Analytics for Business (Coursera)</p>
              <p id="institutionName" class="">
                <b>University Of Colorado Boulder.</b>
              </p>
              <p id="" class="certificationTitle">UX Design Fundamentals (Coursera)</p>
              <p id="institutionName" class="">
                <b>California Institute Of Arts.</b>
              </p>
              <p id="" class="certificationTitle">Visual Elements Of User Interface Design (Coursera)</p>
              <p id="institutionName" class="">
                <b>California Institute Of Arts.</b>
              </p>
              <p id="" class="certificationTitle">Front-End Web UI Frameworks And Tools: Bootstrap 4 (Coursera)</p>
              <p id="institutionName" class="">
                <b>The Hong Kong University Of Science And Technology.</b>
              </p>
              <p id="" class="certificationTitle">Winner Of Forman Computing Society’s Freshmen Gaming Competition (Counter
                Strike)</p>
              <p id="institutionName" class="">
                <b>FCCU FCS 2016.</b>
              </p>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="js">
export default {
  name: "CertificationsAndAchievements",
  data() {
    return {};
  },
};
</script>

<style lang="css" scoped>
.tracking-in-expand {
  -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1)
    1s both;
  animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) 1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-4-17 13:25:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 640px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    color: whitesmoke;
    font-family: "Rubik Mono One", monospace;
    font-size: 30px;
    text-align: center;
  }
  .certificationTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", sans-serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", monospace;
    font-weight: bold;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", sans-serif;
    font-size: 20px;
    margin: 5px;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 300px;
    box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", sans-serif;
    font-size: 25px;
    text-align: center;
  }
  #institutionName {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 641px) and (max-width: 767px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    color: whitesmoke;
    font-family: "Rubik Mono One", monospace;
    font-size: 30px;
    text-align: center;
  }
  .certificationTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", sans-serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", monospace;
    font-weight: bold;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", sans-serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 300px;
    box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", sans-serif;
    font-size: 25px;
    text-align: center;
  }
  #institutionName {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) and (max-width: 1023px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    color: whitesmoke;
    font-family: "Rubik Mono One", monospace;
    font-size: 30px;
    text-align: center;
  }
  .certificationTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", sans-serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", monospace;
    font-weight: bold;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", sans-serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 700px;
    width: 100%; /* Set image width to 100% */
    box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", sans-serif;
    font-size: 25px;
    text-align: center;
  }
  #institutionName {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 1024px) and (max-width: 1279px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    color: whitesmoke;
    font-family: "Rubik Mono One", monospace;
    font-size: 30px;
    text-align: center;
  }
  .certificationTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", sans-serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", monospace;
    font-weight: bold;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", sans-serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 750px;
    width: 100%; /* Set image width to 100% */
    box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", sans-serif;
    font-size: 25px;
    text-align: center;
  }
  .pentagon {
    clip-path: polygon(100% 0, 100% 100%, 31% 100%, 25% 51%, 36% 0);
    width: 100%; /* Set the width of the pentagon container to 100% */
  }
  #institutionName {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Large devices (laptops/desktops, 1280px and up) */
@media only screen and (min-width: 1280px) and (max-width: 1535px) {
  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    color: whitesmoke;
    font-family: "Rubik Mono One", monospace;
    font-size: 30px;
    text-align: center;
  }
  .certificationTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", sans-serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", monospace;
    font-weight: bold;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", sans-serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 750px;
    width: 100%; /* Set image width to 100% */
    box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", sans-serif;
    font-size: 25px;
    text-align: center;
  }
  .pentagon {
    clip-path: polygon(100% 0, 100% 100%, 31% 100%, 25% 51%, 36% 0);
    width: 100%; /* Set the width of the pentagon container to 100% */
  }
  #institutionName {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Extra large devices (large laptops and desktops, 1536px and up) */
@media only screen and (min-width: 1536px) {
  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    color: whitesmoke;
    font-family: "Rubik Mono One", monospace;
    font-size: 30px;
    text-align: center;
  }
  .certificationTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", sans-serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", monospace;
    font-weight: bold;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", sans-serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    margin-top: 50px;
    height: 750px;
    width: 100%; /* Set image width to 100% */
    box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", sans-serif;
    font-size: 25px;
    text-align: center;
  }
  .pentagon {
    margin-top: 50px;
    clip-path: polygon(100% 0, 100% 100%, 31% 100%, 25% 51%, 36% 0);
    width: 100%; /* Set the width of the pentagon container to 100% */
  }
  #institutionName {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik", sans-serif;
    font-size: 18px;
  }
  #workPoints {
    font-family: "Rubik", sans-serif;
    font-size: 18px;
    color: whitesmoke;
  }
}
</style>
