<template>
  <div id="" class="px-0 container-fluid">
    <div id="row" class="grid grid-rows-1">
      <div id="content" class="bg-slate-950">
        <div
          id="content"
          class="grid grid-cols-1 2xl:columns-1 xl:columns-1 lg:columns-1 md:columns-1 sm:columns-1 xs:columns-1"
        >
          <span id="sectionHeading" class="">
            <h1>Educational Background</h1>
          </span>
        </div>
        <div
          id=""
          class="grid grid-cols-3 2xl:columns-3 xl:columns-3 lg:columns-3 md:columns-3 sm:columns-3 xs:columns-3"
        >
          <div id="" class="align-middle text-center">
            <span id="" class="">
              <!-- <p id="" class="companyTitle">Wi-Metrix</p> -->
              <p id="qualification" class="">
                <b>Bachelors Of Computer Science (BCS)</b>
              </p>
              <p id="qualification" class="">2016-2020</p>
              <br />
              <ul id="details" class="">
                <li>
                  Forman Christian College.
                  <br />
                  Final Year Project:<br>Social Media Predictive Analytics System. Used Machine Learning and Predictive Analytics models to predict social media post reach.
                </li>
              </ul>
            </span>
          </div>
          <div id="" class="align-middle text-center">
            <span id="" class="">
              <!-- <p id="" class="companyTitle">Wi-Metrix</p> -->
              <p id="qualification" class="">
                <b>A`Levels</b>
              </p>
              <p id="qualification" class="">2012-2014</p>
              <br />
              <ul id="details" class="">
                <li>
                  Beaconhouse Defence Campus Lahore.
                </li>
              </ul>
            </span>
          </div>
          <div id="" class="align-middle text-center">
            <span id="" class="">
              <!-- <p id="" class="companyTitle">Wi-Metrix</p> -->
              <p id="qualification" class="">
                <b>O`Levels</b>
              </p>
              <p id="qualification" class="">2008-2012</p>
              <br />
              <ul id="details" class="">
                <li>
                  DHA Senior School For Boys Lahore.
                  <br />
                </li>
              </ul>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="js">
export default {
  // components: { humanVerification },
  name: "EducationalBackground",
  data() {
    return {
      // name: "Hamza",
      // date: new Date().getDate(),
      // month: new Date().getMonth(),
      // time: new Date().toTimeString(),
      // day: new Date().getDay(),
      // year: new Date().getFullYear(),
      // bold: "<b> Bold Text </b>",
      // blueText: "blueText",
      // pinkText: "pinkText",
      // highlightColor: "orange",
    };
  },
};
</script>

<style lang="css" scoped>
.tracking-in-expand {
  -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1)
    1s both;
  animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) 1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-4-17 13:25:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 640px) {

  body {
    margin: 0;
  }

  #content {
    /* margin-bottom: 17px; */
    padding-bottom: 15px;
  }

  #details {
    font-family: "Rubik", serif;
    font-size: 16px;
    font-optical-sizing: auto;
    font-weight: 300;
    font-style: normal;
    color: whitesmoke;
  }

  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 25px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
    padding-top: 15px;
  }

  #qualification {
    color: #0770e0;
    /* font-family: "Rubik", serif; */
    font-size: 18px;
    font-family: "Rubik Mono One", serif;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
}

/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 641px) and (max-width: 767px) {

  body {
    margin: 0;
  }

  #content {
    /* margin-bottom: 17px; */
    padding-bottom: 15px;
  }

  #details {
    font-family: "Rubik", serif;
    font-size: 16px;
    font-optical-sizing: auto;
    font-weight: 300;
    font-style: normal;
    color: whitesmoke;
  }

  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 25px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
    padding-top: 15px;
  }

  #qualification {
    color: #0770e0;
    /* font-family: "Rubik", serif; */
    font-size: 18px;
    font-family: "Rubik Mono One", serif;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
}

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) and (max-width: 1023px) {

  body {
    margin: 0;
  }

  #content {
    /* margin-bottom: 17px; */
    padding-bottom: 15px;
  }

  #details {
    font-family: "Rubik", serif;
    font-size: 16px;
    font-optical-sizing: auto;
    font-weight: 300;
    font-style: normal;
    color: whitesmoke;
  }

  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 25px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
    padding-top: 15px;
  }

  #qualification {
    color: #0770e0;
    /* font-family: "Rubik", serif; */
    font-size: 18px;
    font-family: "Rubik Mono One", serif;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 1024px) and (max-width: 1279px) {

  body {
    margin: 0;
  }

  #content {
    /* margin-bottom: 17px; */
    padding-bottom: 15px;
  }

  #details {
    font-family: "Rubik", serif;
    font-size: 16px;
    font-optical-sizing: auto;
    font-weight: 300;
    font-style: normal;
    color: whitesmoke;
  }

  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 25px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
    padding-top: 15px;
  }

  #qualification {
    color: #0770e0;
    /* font-family: "Rubik", serif; */
    font-size: 18px;
    font-family: "Rubik Mono One", serif;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
}

/* Large devices (laptops/desktops, 1280px and up) */
@media only screen and (min-width: 1280px) and (max-width: 1535px) {

  body {
    margin: 0;
  }

  #content {
    /* margin-bottom: 17px; */
    padding-bottom: 15px;
  }

  #details {
    font-family: "Rubik", serif;
    font-size: 16px;
    font-optical-sizing: auto;
    font-weight: 300;
    font-style: normal;
    color: whitesmoke;
  }

  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 25px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
    padding-top: 15px;
  }

  #qualification {
    color: #0770e0;
    /* font-family: "Rubik", serif; */
    font-size: 18px;
    font-family: "Rubik Mono One", serif;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
}

/* Extra large devices (large laptops and desktops, 1536px and up) */
@media only screen and (min-width: 1536px) {

  body {
    margin: 0;
  }

  #content {
    /* margin-bottom: 17px; */
    padding-bottom: 15px;
  }

  #details {
    font-family: "Rubik", serif;
    font-size: 16px;
    font-optical-sizing: auto;
    font-weight: 300;
    font-style: normal;
    color: whitesmoke;
  }

  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 25px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
    padding-top: 15px;
  }

  #qualification {
    color: #0770e0;
    /* font-family: "Rubik", serif; */
    font-size: 18px;
    font-family: "Rubik Mono One", serif;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
}
</style>
