<template>
  <div id="" class="px-0 container-fluid">
    <div id="row" class="grid grid-rows-1">
      <div id="content" class="bg-slate-950">
        <div
          id=""
          class="grid grid-cols-1 2xl:columns-1 xl:columns-1 lg:columns-1 md:columns-1 sm:columns-1 xs:columns-1"
        >
          <span id="sectionHeading" class="">
            <h1>Supporting Skills And Strengths</h1>
          </span>
        </div>
        <div
          id=""
          class="grid grid-cols-3 2xl:columns-3 xl:columns-3 lg:columns-3 md:columns-3 sm:columns-3 xs:columns-3"
        >
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="devicon:nuxtjs" width="128" height="128" />
              Nuxt.js
            </span>
          </div>
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="logos:websocket" width="256" height="193" />
              WebSockets
            </span>
          </div>
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="flat-color-icons:linux" width="48" height="48" />
              Linux
            </span>
          </div>
        </div>
        <div
          id=""
          class="grid grid-cols-3 2xl:columns-3 xl:columns-3 lg:columns-3 md:columns-3 sm:columns-3 xs:columns-3"
        >
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="devicon:html5-wordmark" width="128" height="128" />
              HTML
            </span>
          </div>
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="devicon:bootstrap" width="128" height="128" />
              BootStrap
            </span>
          </div>
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="devicon:css3-wordmark" width="128" height="128" />
              CSS
            </span>
          </div>
        </div>
        <div
          id=""
          class="grid grid-cols-1 2xl:columns-1 xl:columns-1 lg:columns-1 md:columns-1 sm:columns-1 xs:columns-1"
        >
          <div id="" class="align-middle text-center">
            <span id = 'positionDescription' class = "">
              <Icon name="devicon:tailwindcss" width="128" height="128" />
              Tailwind CSS
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="js">
export default {
  // components: { humanVerification },
  name: "SupportingSkillsAndStrengths",
  data() {
    return {
      // name: "Hamza",
      // date: new Date().getDate(),
      // month: new Date().getMonth(),
      // time: new Date().toTimeString(),
      // day: new Date().getDay(),
      // year: new Date().getFullYear(),
      // bold: "<b> Bold Text </b>",
      // blueText: "blueText",
      // pinkText: "pinkText",
      // highlightColor: "orange",
    };
  },
};
</script>

<style lang="css" scoped>
.tracking-in-expand {
  -webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1)
    1s both;
  animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.61, 0.355, 1) 1s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-4-17 13:25:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-expand
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 640px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 30px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
  .companyTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", serif;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", serif;
    font-size: 20px;
    margin: 5px;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 300px;
    box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", serif;
    font-size: 25px;
    text-align: center;
  }
  #positionDescription {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 641px) and (max-width: 767px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 30px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
  .companyTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", serif;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 300px;
    box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", serif;
    font-size: 25px;
    text-align: center;
  }
  #positionDescription {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) and (max-width: 1023px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 30px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
  .companyTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", serif;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 700px;
    width: 100%; /* Set image width to 100% */
    box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: 10px 10px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", serif;
    font-size: 25px;
    text-align: center;
  }
  #positionDescription {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 1024px) and (max-width: 1279px) {
  body {
    margin: 0;
  }

  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 30px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
  .companyTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", serif;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 750px;
    width: 100%; /* Set image width to 100% */
    box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", serif;
    font-size: 25px;
    text-align: center;
  }
  .pentagon {
    clip-path: polygon(100% 0, 100% 100%, 31% 100%, 25% 51%, 36% 0);
    width: 100%; /* Set the width of the pentagon container to 100% */
  }
  #positionDescription {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Large devices (laptops/desktops, 1280px and up) */
@media only screen and (min-width: 1280px) and (max-width: 1535px) {
  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 30px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }
  .companyTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", serif;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    height: 750px;
    width: 100%; /* Set image width to 100% */
    box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", serif;
    font-size: 25px;
    text-align: center;
  }
  .pentagon {
    clip-path: polygon(100% 0, 100% 100%, 31% 100%, 25% 51%, 36% 0);
    width: 100%; /* Set the width of the pentagon container to 100% */
  }
  #positionDescription {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
  #workPoints {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
}

/* Extra large devices (large laptops and desktops, 1536px and up) */
@media only screen and (min-width: 1536px) {
  #introSection {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-top: 20%;
  }
  #sectionHeading {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik Mono One", serif;
    font-size: 30px;
    font-weight: 400;
    font-style: normal;
    text-align: center;
  }

  .companyTitle {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    /* font-family: "Rubik", serif; */
    font-size: 25px;
    font-family: "Rubik Mono One", serif;
  }
  .formInput {
    border: 1px solid;
    border-radius: 15px;
    background: transparent;
    border-style: solid;
    border-color: #1858e2;
    font-family: "Rubik", serif;
    font-size: 20px;
    margin: 5px;
    overflow-x: scroll;
    padding: 4px;
  }
  .icons {
    font-size: 25px;
  }
  .icons:hover {
    opacity: 50%;
  }
  .images {
    margin-top: 50px;
    height: 750px;
    width: 100%; /* Set image width to 100% */
    box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -webkit-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
    -moz-box-shadow: -4px 5px 5px 0px rgba(255, 0, 0, 0.75);
  }
  .introDetails {
    font-size: 16px;
  }
  #moto {
    font-family: "Rubik", serif;
    font-size: 25px;
    text-align: center;
  }
  .pentagon {
    margin-top: 50px;
    clip-path: polygon(100% 0, 100% 100%, 31% 100%, 25% 51%, 36% 0);
    width: 100%; /* Set the width of the pentagon container to 100% */
  }
  #positionDescription {
    background: #1858e2;
    background: linear-gradient(to bottom right, #1858e2 0%, #b316e7 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-family: "Rubik", serif;
    font-size: 18px;
  }
  #workPoints {
    font-family: "Rubik", serif;
    font-size: 18px;
    color: whitesmoke;
  }
}
</style>
